name: Compile for ESP32

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          esp-idf-version: v5.1.1

      - name: Set target to ESP32
        run: |
          idf.py set-target esp32

      - name: Build project
        run: |
          idf.py fullclean build
