name: QEMU Unity Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install QEMU system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgcrypt20 \
            libglib2.0-0 \
            libpixman-1-0 \
            libslirp0 \
            libsdl2-2.0-0 \
            libsdl2-dev

      - name: Clone ESP-IDF
        run: git clone --depth 1 https://github.com/espressif/esp-idf.git $HOME/esp-idf

      - name: Install Python & QEMU tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python $HOME/esp-idf/tools/idf_tools.py install-python-env --features=core,pytest
          python $HOME/esp-idf/tools/idf_tools.py install qemu-xtensa qemu-riscv32
          python $HOME/esp-idf/tools/idf_tools.py install --targets=all
          eval "$HOME/esp-idf/tools/idf_tools.py export"

      - name: Build and run unit tests
        run: sh run-tests.sh
